version: "2"
services:
  postgres:
    image: postgres:13.4
    container_name: postgres-test
    volumes:
      - "./docker/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=sample-todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
